# Generated by Django 3.2.4 on 2021-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('tel', models.CharField(max_length=150, unique=True, verbose_name='Telefono')),
                ('Localidad', models.CharField(max_length=150, unique=True, verbose_name='Localidad')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'ContactUs',
                'ordering': ['id'],
            },
        ),
    ]
